skidbot_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# skidbot_joint_velocity_controller:
#   type: JointVelocityController
#   joint: rear_right_wheel
#   pid:
#     p: 5.0
#     i: 20.0

skidbot_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25
  publish_cmd: True

  k_l: 0.1
  k_r: 0.1

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: False # later we will set this to false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 5.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10.0   # rad/s^2
