<?xml version="1.0"?>

<robot name="skidbot" xmlns:xacro="http://ros.org/wiki/xacro">

<!--   <xacro:macro name="qbo">   -->

  <xacro:include filename="$(find skidbot_description)/urdf/common_properties.xacro" />
  <xacro:include filename="$(find skidbot_description)/gazebo/skidbot.gazebo.xacro" />

  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.2" />
  <!-- <xacro:property name="track" value="0.245" /> -->
  <xacro:property name="track" value="0.28" />
  <xacro:property name="wheel_vertical_offset" value="0.0325" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />
  <xacro:property name="wheel_radius" value="0.0325" />
  <xacro:property name="wheel_width" value="0.025" />

  <xacro:property name="chassis_length" value="0.40" />
  <xacro:property name="chassis_width" value="0.27" />
  <xacro:property name="chassis_height" value="0.04" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/ruedaCentrada.stl"/>
        </geometry>
        <material name="green" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <selfCollide>false</selfCollide>
      <mu1 value="0.5"/>
      <mu2 value="0.5"/>
      <kp value="10000000.0" />
      <kd value="1" />
      <fdir1 value="1 0 0"/>
    </gazebo>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <!-- In reality, Jackal has only two motors, one per side. However, it's more
         straightforward for Gazebo to simulate as if there's an actuator per wheel. -->
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>


<xacro:wheel prefix="front_left">
  <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:wheel>
<xacro:wheel prefix="front_right">
  <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:wheel>
<xacro:wheel prefix="rear_left">
  <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:wheel>
<xacro:wheel prefix="rear_right">
  <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:wheel>

<!-- Defining the fixed base link of the robot -->


<link name="base_link"></link>

<joint name="base_link_joint" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="base_link"/>
  <child link="chassis_link" />
</joint>


<link name="chassis_link">
  <visual>
    <geometry>
      <!-- new mesh -->
      <mesh filename="package://skidbot_description/meshes/baseCentrada1.stl" />
      <material name="white"/>
    </geometry>

	 <origin xyz="0.0 0 0.0325" rpy="0 0 ${PI/2}"/>
      </visual>
      <collision>
  <origin xyz="0 0 ${0.0325+chassis_height/2}"/>
  <geometry>
    <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
  </geometry>
</collision>
      <inertial>
        <!-- COM experimentally determined -->
        <origin xyz="0.0 0 0"/>
        <mass value="2.4"/> <!-- 2.4/2.6 kg for small/big battery pack -->

        <inertia ixx="0.019995" ixy="0.0" ixz="0.0"
                 iyy="0.019995" iyz="0.0"
                 izz="0.03675" />
      </inertial>
</link>

<link name="lidar_plate_link">
  <visual>
    <geometry>
      <box size="0.2 0.2 0.005" />
    </geometry>
    <origin xyz="0 0 0" />
    <material name="white" />
  </visual>
</link>
<joint name="lidar_plate_joint" type="fixed">
  <parent link="chassis_link" />
  <child link="lidar_plate_link" />
  <origin xyz="0 0 0.1" />
</joint>



    <!-- <joint name="front_left_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="skidbot_wheel_left_front_link"/>
      <origin xyz="-0.1475 0.1 0.0325" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="skidbot_wheel_left_front_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
    <geometry>
      <mesh filename="package://skidbot_description/meshes/jackal-wheel.stl"/>
    </geometry>
    <material name="black" />
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.477"/>
    <inertia
      ixx="0.0013" ixy="0" ixz="0"
      iyy="0.0024" iyz="0"
      izz="0.0013"/>
  </inertial>
</link> -->

<!--
    <link name="skidbot_wheel_left_front_link">
      <visual>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/ruedaCentrada.stl"/>
       <material name="black"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.0125" radius="0.0325"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
      </inertial>
    </link> -->


    <!-- <joint name="front_right_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="skidbot_wheel_right_front_link"/>
      <origin xyz="0.1475 0.1 0.0325" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>
    <link name="skidbot_wheel_right_front_link"> -->
      <!-- <visual>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/ruedaCentrada.stl"/>
       <material name="black"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.0125" radius="0.0325"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
      </inertial> -->
      <!-- <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link> -->

    <!-- <joint name="rear_left_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="skidbot_wheel_left_rear_link"/>
      <origin xyz="-0.1475 -0.1 0.0325" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>
    <link name="skidbot_wheel_left_rear_link"> -->
      <!-- <visual>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/ruedaCentrada.stl"/>
       <material name="black"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.0125" radius="0.0325"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
      </inertial> -->
      <!-- <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link> -->

    <!-- <joint name="rear_right_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="skidbot_wheel_right_rear_link"/>
      <origin xyz="0.1475 -0.1 0.0325" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>
    <link name="skidbot_wheel_right_rear_link"> -->
      <!-- <visual>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/ruedaCentrada.stl"/>
       <material name="black"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.0125" radius="0.0325"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
      </inertial> -->
      <!-- <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <mesh filename="package://skidbot_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link> -->

    <link name="imu_link">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
      </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
      <parent link="chassis_link" />
      <child link="imu_link" />
    </joint>

    <!-- TODO: Same note as applies to imu_link -->
    <link name="navsat_link">
      <visual>
        <geometry>
          <cylinder radius="0.026" length="0.016" />
        </geometry>
        <origin xyz="0 0 0.0" />
        <material name="black" />
      </visual>
    </link>
    <joint name="navsat_joint" type="fixed">
      <parent link="chassis_link" />
      <child link="navsat_link" />
      <origin xyz="-0.180 0.126 0.1815" />
    </joint>


    <joint name="rplidar_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <parent link="lidar_plate_link"/>
        <child link="laser"/>
      </joint>

      <!-- rplidar Laser -->
      <link name="laser">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="package://skidbot_description/meshes/rplidar_a1.dae" />
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 -0.05" rpy="0 0 0"/>
          <geometry>
            <mesh filename="package://skidbot_description/meshes/rplidar_a1.dae"  />
          </geometry>
        </visual>

        <inertial>
          <mass value="1e-5" />
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
        </inertial>
      </link>


</robot>
